# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: /blog/:title

# Setup
exclude: [Gemfile, Gemfile.lock]
title: Mahdi Hussein
url: http://mahdihusse.in
author:
  name: 'Mahdi Hussein'
  email: 'm@hdihusse.in'

paginate: 5

# Custom vars
social:
  github: husseinm
  twitter: MahdiMHussein
